function [] = printToFile(fileId, lineNumber, values, newline, delim)
% printToFile(fileId, lineNumber, values, newline, delim)
% prints the values from the struct values into file at fileId. The
% lineNumber given is used for an excel formulae that may need to be
% written. newLine and delim (delimiter) values are given for ease of
% change in case a different format is needed
% required by GIANT

dobCell = ['C', num2str(lineNumber)];
studyDateCell = ['E', num2str(lineNumber)];

ageFormula = ['=(MONTH(', studyDateCell ,') - MONTH(', dobCell, '))+(YEAR(', studyDateCell, ') - YEAR(', dobCell, '))*12'];

format = struct(...
    'patientId', '%s',...
    'patientSex', '%s',...
    'patientDob', '%s',...
    'sequenceNumber', '%d',...
    'studyDate', '%s',...
    'ageInMonths', '%s',... %since formula is string
    'modality', '%s',...
    'studyName', '%s',...
    'seriesName', '%s',...
    'fileName', '%s',...
    'measurementA', '%6.1f',...
    'measurementB', '%6.1f',...
    'measurementC', '%6.1f',...
    'measurementD', '%6.1f',...
    'measurementE', '%6.1f',...
    'measurementF', '%6.1f',...
    'measurementG', '%6.1f',...
    'measurementH', '%6.1f',...
    'measurementI', '%6.1f',...
    'measurementJ', '%6.1f',...
    'refLength', '%6.1f',...
    'pylorusX', '%6.1f',...
    'pylorusY', '%6.1f',...
    'pointAX', '%6.1f',...
    'pointAY', '%6.1f',...
    'pointBX', '%6.1f',...
    'pointBY', '%6.1f',...
    'pointCX', '%6.1f',...
    'pointCY', '%6.1f',...
    'pointDX', '%6.1f',...
    'pointDY', '%6.1f');

line = strcat(...
    sprintf(format.patientId, values.patientId), delim,...
    sprintf(format.patientSex, values.patientSex), delim,...
    sprintf(format.patientDob, values.patientDob), delim,...
    sprintf(format.sequenceNumber, values.sequenceNumber), delim,...
    sprintf(format.studyDate, values.studyDate), delim,...
    sprintf(format.ageInMonths, ageFormula), delim,...
    sprintf(format.modality, values.modality), delim,...
    sprintf(format.studyName, values.studyName), delim,...
    sprintf(format.seriesName, values.seriesName), delim,...
    sprintf(format.fileName, values.fileName), delim,...
    sprintf(format.measurementA, values.measurementA), delim,...
    sprintf(format.measurementB, values.measurementB), delim,...
    sprintf(format.measurementC, values.measurementC), delim,...
    sprintf(format.measurementD, values.measurementD), delim,...
    sprintf(format.measurementE, values.measurementE), delim,...
    sprintf(format.measurementF, values.measurementF), delim,...
    sprintf(format.measurementG, values.measurementG), delim,...
    sprintf(format.measurementH, values.measurementH), delim,...
    sprintf(format.measurementI, values.measurementI), delim,...
    sprintf(format.measurementJ, values.measurementJ), delim,...
    sprintf(format.refLength, values.refLength), delim,...
    sprintf(format.pylorusX, values.pylorusX), delim,...
    sprintf(format.pylorusY, values.pylorusY), delim,...
    sprintf(format.pointAX, values.pointAX), delim,...
    sprintf(format.pointAY, values.pointAY), delim,...
    sprintf(format.pointBX, values.pointBX), delim,...
    sprintf(format.pointBY, values.pointBY), delim,...
    sprintf(format.pointCX, values.pointCX), delim,...
    sprintf(format.pointCY, values.pointCY), delim,...
    sprintf(format.pointDX, values.pointDX), delim,...
    sprintf(format.pointDY, values.pointDY));

fprintf(fileId, line);

fprintf(fileId, newline);
    
end

