function [ values ] = setFields(cellValues)
%[ values ] = setFields(cellValues)
% takes in the values of a row cells read in, in order, and returns them,
% conveinently stored in a struct

values = struct(...
    'patientId', cellValues{1},...
    'patientSex', cellValues{2},...
    'patientDob', cellValues{3},... 
    'sequenceNumber', str2double(cellValues{4}),...
    'studyDate', cellValues{5},...
    'modality', cellValues{7},... % cellValues{6} skipped; age formula (must be updated to have proper cell references)
    'studyName', cellValues{8},...
    'seriesName', cellValues{9},...
    'fileName', cellValues{10},...
    'measurementA', str2double(cellValues{11}),...
    'measurementB', str2double(cellValues{12}),...
    'measurementC', str2double(cellValues{13}),...
    'measurementD', str2double(cellValues{14}),...
    'measurementE', str2double(cellValues{15}),...
    'measurementF', str2double(cellValues{16}),...
    'measurementG', str2double(cellValues{17}),...
    'measurementH', str2double(cellValues{18}),...
    'measurementI', str2double(cellValues{19}),...
    'measurementJ', str2double(cellValues{20}),...
    'refLength', str2double(cellValues{21}),...
    'pylorusX', str2double(cellValues{22}),...
    'pylorusY', str2double(cellValues{23}),...
    'pointAX', str2double(cellValues{24}),...
    'pointAY', str2double(cellValues{25}),...
    'pointBX', str2double(cellValues{26}),...
    'pointBY', str2double(cellValues{27}),...
    'pointCX', str2double(cellValues{28}),...
    'pointCY', str2double(cellValues{29}),...
    'pointDX', str2double(cellValues{30}),...
    'pointDY', str2double(cellValues{31}));


end

